<?php
if (!isset($_GET['token']) || $_GET['token'] !== 'karaja2026fix') die('403');
$pdo = new PDO('mysql:host=sql111.infinityfree.com;dbname=if0_41274369_karajaerp;charset=utf8mb4', 'if0_41274369', 'moit2030', [PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION]);
header('Content-Type: text/plain; charset=utf-8');
$ins=0; $upd=0;
$chk = $pdo->prepare('SELECT id FROM branch_stock WHERE branch_id=1 AND product_id=?');
$upd_s = $pdo->prepare('UPDATE branch_stock SET quantity=?, updated_at=NOW() WHERE branch_id=1 AND product_id=?');
$ins_s = $pdo->prepare('INSERT INTO branch_stock (branch_id, product_id, quantity, created_at, updated_at) VALUES (1, ?, ?, NOW(), NOW())');
$chk->execute([9]); if($chk->fetch()) { $upd_s->execute([10,9]); $upd++; } else { $ins_s->execute([9,10]); $ins++; }
$chk->execute([10]); if($chk->fetch()) { $upd_s->execute([0,10]); $upd++; } else { $ins_s->execute([10,0]); $ins++; }
$chk->execute([11]); if($chk->fetch()) { $upd_s->execute([0,11]); $upd++; } else { $ins_s->execute([11,0]); $ins++; }
$chk->execute([12]); if($chk->fetch()) { $upd_s->execute([0,12]); $upd++; } else { $ins_s->execute([12,0]); $ins++; }
$chk->execute([13]); if($chk->fetch()) { $upd_s->execute([0,13]); $upd++; } else { $ins_s->execute([13,0]); $ins++; }
$chk->execute([14]); if($chk->fetch()) { $upd_s->execute([0,14]); $upd++; } else { $ins_s->execute([14,0]); $ins++; }
$chk->execute([15]); if($chk->fetch()) { $upd_s->execute([0,15]); $upd++; } else { $ins_s->execute([15,0]); $ins++; }
$chk->execute([16]); if($chk->fetch()) { $upd_s->execute([0,16]); $upd++; } else { $ins_s->execute([16,0]); $ins++; }
$chk->execute([17]); if($chk->fetch()) { $upd_s->execute([0,17]); $upd++; } else { $ins_s->execute([17,0]); $ins++; }
$chk->execute([18]); if($chk->fetch()) { $upd_s->execute([0,18]); $upd++; } else { $ins_s->execute([18,0]); $ins++; }
$chk->execute([19]); if($chk->fetch()) { $upd_s->execute([0,19]); $upd++; } else { $ins_s->execute([19,0]); $ins++; }
$chk->execute([20]); if($chk->fetch()) { $upd_s->execute([1,20]); $upd++; } else { $ins_s->execute([20,1]); $ins++; }
$chk->execute([21]); if($chk->fetch()) { $upd_s->execute([0,21]); $upd++; } else { $ins_s->execute([21,0]); $ins++; }
$chk->execute([22]); if($chk->fetch()) { $upd_s->execute([0,22]); $upd++; } else { $ins_s->execute([22,0]); $ins++; }
$chk->execute([23]); if($chk->fetch()) { $upd_s->execute([0,23]); $upd++; } else { $ins_s->execute([23,0]); $ins++; }
$chk->execute([24]); if($chk->fetch()) { $upd_s->execute([19,24]); $upd++; } else { $ins_s->execute([24,19]); $ins++; }
$chk->execute([25]); if($chk->fetch()) { $upd_s->execute([11,25]); $upd++; } else { $ins_s->execute([25,11]); $ins++; }
$chk->execute([26]); if($chk->fetch()) { $upd_s->execute([0,26]); $upd++; } else { $ins_s->execute([26,0]); $ins++; }
$chk->execute([27]); if($chk->fetch()) { $upd_s->execute([0,27]); $upd++; } else { $ins_s->execute([27,0]); $ins++; }
$chk->execute([28]); if($chk->fetch()) { $upd_s->execute([0,28]); $upd++; } else { $ins_s->execute([28,0]); $ins++; }
$chk->execute([29]); if($chk->fetch()) { $upd_s->execute([0,29]); $upd++; } else { $ins_s->execute([29,0]); $ins++; }
$chk->execute([30]); if($chk->fetch()) { $upd_s->execute([0,30]); $upd++; } else { $ins_s->execute([30,0]); $ins++; }
$chk->execute([31]); if($chk->fetch()) { $upd_s->execute([0,31]); $upd++; } else { $ins_s->execute([31,0]); $ins++; }
$chk->execute([32]); if($chk->fetch()) { $upd_s->execute([0,32]); $upd++; } else { $ins_s->execute([32,0]); $ins++; }
$chk->execute([33]); if($chk->fetch()) { $upd_s->execute([5,33]); $upd++; } else { $ins_s->execute([33,5]); $ins++; }
$chk->execute([34]); if($chk->fetch()) { $upd_s->execute([7,34]); $upd++; } else { $ins_s->execute([34,7]); $ins++; }
$chk->execute([35]); if($chk->fetch()) { $upd_s->execute([0,35]); $upd++; } else { $ins_s->execute([35,0]); $ins++; }
$chk->execute([36]); if($chk->fetch()) { $upd_s->execute([64,36]); $upd++; } else { $ins_s->execute([36,64]); $ins++; }
$chk->execute([37]); if($chk->fetch()) { $upd_s->execute([4,37]); $upd++; } else { $ins_s->execute([37,4]); $ins++; }
$chk->execute([38]); if($chk->fetch()) { $upd_s->execute([6,38]); $upd++; } else { $ins_s->execute([38,6]); $ins++; }
$chk->execute([39]); if($chk->fetch()) { $upd_s->execute([4,39]); $upd++; } else { $ins_s->execute([39,4]); $ins++; }
$chk->execute([40]); if($chk->fetch()) { $upd_s->execute([0,40]); $upd++; } else { $ins_s->execute([40,0]); $ins++; }
$chk->execute([41]); if($chk->fetch()) { $upd_s->execute([0,41]); $upd++; } else { $ins_s->execute([41,0]); $ins++; }
$chk->execute([42]); if($chk->fetch()) { $upd_s->execute([0,42]); $upd++; } else { $ins_s->execute([42,0]); $ins++; }
$chk->execute([43]); if($chk->fetch()) { $upd_s->execute([0,43]); $upd++; } else { $ins_s->execute([43,0]); $ins++; }
$chk->execute([44]); if($chk->fetch()) { $upd_s->execute([0,44]); $upd++; } else { $ins_s->execute([44,0]); $ins++; }
$chk->execute([45]); if($chk->fetch()) { $upd_s->execute([0,45]); $upd++; } else { $ins_s->execute([45,0]); $ins++; }
$chk->execute([46]); if($chk->fetch()) { $upd_s->execute([0,46]); $upd++; } else { $ins_s->execute([46,0]); $ins++; }
$chk->execute([47]); if($chk->fetch()) { $upd_s->execute([0,47]); $upd++; } else { $ins_s->execute([47,0]); $ins++; }
$chk->execute([48]); if($chk->fetch()) { $upd_s->execute([0,48]); $upd++; } else { $ins_s->execute([48,0]); $ins++; }
$chk->execute([49]); if($chk->fetch()) { $upd_s->execute([0,49]); $upd++; } else { $ins_s->execute([49,0]); $ins++; }
$chk->execute([50]); if($chk->fetch()) { $upd_s->execute([1,50]); $upd++; } else { $ins_s->execute([50,1]); $ins++; }
$chk->execute([51]); if($chk->fetch()) { $upd_s->execute([0,51]); $upd++; } else { $ins_s->execute([51,0]); $ins++; }
$chk->execute([52]); if($chk->fetch()) { $upd_s->execute([0,52]); $upd++; } else { $ins_s->execute([52,0]); $ins++; }
$chk->execute([53]); if($chk->fetch()) { $upd_s->execute([0,53]); $upd++; } else { $ins_s->execute([53,0]); $ins++; }
$chk->execute([54]); if($chk->fetch()) { $upd_s->execute([0,54]); $upd++; } else { $ins_s->execute([54,0]); $ins++; }
$chk->execute([55]); if($chk->fetch()) { $upd_s->execute([0,55]); $upd++; } else { $ins_s->execute([55,0]); $ins++; }
$chk->execute([56]); if($chk->fetch()) { $upd_s->execute([0,56]); $upd++; } else { $ins_s->execute([56,0]); $ins++; }
$chk->execute([57]); if($chk->fetch()) { $upd_s->execute([3,57]); $upd++; } else { $ins_s->execute([57,3]); $ins++; }
$chk->execute([58]); if($chk->fetch()) { $upd_s->execute([0,58]); $upd++; } else { $ins_s->execute([58,0]); $ins++; }
$chk->execute([59]); if($chk->fetch()) { $upd_s->execute([0,59]); $upd++; } else { $ins_s->execute([59,0]); $ins++; }
$chk->execute([60]); if($chk->fetch()) { $upd_s->execute([0,60]); $upd++; } else { $ins_s->execute([60,0]); $ins++; }
$chk->execute([61]); if($chk->fetch()) { $upd_s->execute([4,61]); $upd++; } else { $ins_s->execute([61,4]); $ins++; }
$chk->execute([62]); if($chk->fetch()) { $upd_s->execute([0,62]); $upd++; } else { $ins_s->execute([62,0]); $ins++; }
$chk->execute([63]); if($chk->fetch()) { $upd_s->execute([6,63]); $upd++; } else { $ins_s->execute([63,6]); $ins++; }
$chk->execute([64]); if($chk->fetch()) { $upd_s->execute([5,64]); $upd++; } else { $ins_s->execute([64,5]); $ins++; }
$chk->execute([65]); if($chk->fetch()) { $upd_s->execute([0,65]); $upd++; } else { $ins_s->execute([65,0]); $ins++; }
$chk->execute([66]); if($chk->fetch()) { $upd_s->execute([0,66]); $upd++; } else { $ins_s->execute([66,0]); $ins++; }
$chk->execute([67]); if($chk->fetch()) { $upd_s->execute([0,67]); $upd++; } else { $ins_s->execute([67,0]); $ins++; }
$chk->execute([68]); if($chk->fetch()) { $upd_s->execute([0,68]); $upd++; } else { $ins_s->execute([68,0]); $ins++; }
$chk->execute([69]); if($chk->fetch()) { $upd_s->execute([0,69]); $upd++; } else { $ins_s->execute([69,0]); $ins++; }
$chk->execute([70]); if($chk->fetch()) { $upd_s->execute([0,70]); $upd++; } else { $ins_s->execute([70,0]); $ins++; }
$chk->execute([71]); if($chk->fetch()) { $upd_s->execute([0,71]); $upd++; } else { $ins_s->execute([71,0]); $ins++; }
$chk->execute([72]); if($chk->fetch()) { $upd_s->execute([0,72]); $upd++; } else { $ins_s->execute([72,0]); $ins++; }
$chk->execute([73]); if($chk->fetch()) { $upd_s->execute([0,73]); $upd++; } else { $ins_s->execute([73,0]); $ins++; }
$chk->execute([74]); if($chk->fetch()) { $upd_s->execute([0,74]); $upd++; } else { $ins_s->execute([74,0]); $ins++; }
$chk->execute([75]); if($chk->fetch()) { $upd_s->execute([2,75]); $upd++; } else { $ins_s->execute([75,2]); $ins++; }
$chk->execute([76]); if($chk->fetch()) { $upd_s->execute([0,76]); $upd++; } else { $ins_s->execute([76,0]); $ins++; }
$chk->execute([77]); if($chk->fetch()) { $upd_s->execute([19,77]); $upd++; } else { $ins_s->execute([77,19]); $ins++; }
$chk->execute([78]); if($chk->fetch()) { $upd_s->execute([0,78]); $upd++; } else { $ins_s->execute([78,0]); $ins++; }
$chk->execute([79]); if($chk->fetch()) { $upd_s->execute([0,79]); $upd++; } else { $ins_s->execute([79,0]); $ins++; }
$chk->execute([80]); if($chk->fetch()) { $upd_s->execute([0,80]); $upd++; } else { $ins_s->execute([80,0]); $ins++; }
$chk->execute([81]); if($chk->fetch()) { $upd_s->execute([0,81]); $upd++; } else { $ins_s->execute([81,0]); $ins++; }
$chk->execute([82]); if($chk->fetch()) { $upd_s->execute([3,82]); $upd++; } else { $ins_s->execute([82,3]); $ins++; }
$chk->execute([83]); if($chk->fetch()) { $upd_s->execute([0,83]); $upd++; } else { $ins_s->execute([83,0]); $ins++; }
$chk->execute([84]); if($chk->fetch()) { $upd_s->execute([0,84]); $upd++; } else { $ins_s->execute([84,0]); $ins++; }
$chk->execute([85]); if($chk->fetch()) { $upd_s->execute([0,85]); $upd++; } else { $ins_s->execute([85,0]); $ins++; }
$chk->execute([86]); if($chk->fetch()) { $upd_s->execute([7,86]); $upd++; } else { $ins_s->execute([86,7]); $ins++; }
$chk->execute([87]); if($chk->fetch()) { $upd_s->execute([0,87]); $upd++; } else { $ins_s->execute([87,0]); $ins++; }
$chk->execute([88]); if($chk->fetch()) { $upd_s->execute([0,88]); $upd++; } else { $ins_s->execute([88,0]); $ins++; }
$chk->execute([89]); if($chk->fetch()) { $upd_s->execute([0,89]); $upd++; } else { $ins_s->execute([89,0]); $ins++; }
$chk->execute([90]); if($chk->fetch()) { $upd_s->execute([0,90]); $upd++; } else { $ins_s->execute([90,0]); $ins++; }
$chk->execute([91]); if($chk->fetch()) { $upd_s->execute([0,91]); $upd++; } else { $ins_s->execute([91,0]); $ins++; }
$chk->execute([92]); if($chk->fetch()) { $upd_s->execute([2,92]); $upd++; } else { $ins_s->execute([92,2]); $ins++; }
$chk->execute([93]); if($chk->fetch()) { $upd_s->execute([1,93]); $upd++; } else { $ins_s->execute([93,1]); $ins++; }
$chk->execute([94]); if($chk->fetch()) { $upd_s->execute([2,94]); $upd++; } else { $ins_s->execute([94,2]); $ins++; }
$chk->execute([95]); if($chk->fetch()) { $upd_s->execute([1,95]); $upd++; } else { $ins_s->execute([95,1]); $ins++; }
$chk->execute([96]); if($chk->fetch()) { $upd_s->execute([1,96]); $upd++; } else { $ins_s->execute([96,1]); $ins++; }
$chk->execute([97]); if($chk->fetch()) { $upd_s->execute([2,97]); $upd++; } else { $ins_s->execute([97,2]); $ins++; }
$chk->execute([98]); if($chk->fetch()) { $upd_s->execute([0,98]); $upd++; } else { $ins_s->execute([98,0]); $ins++; }
$chk->execute([99]); if($chk->fetch()) { $upd_s->execute([0,99]); $upd++; } else { $ins_s->execute([99,0]); $ins++; }
$chk->execute([100]); if($chk->fetch()) { $upd_s->execute([5,100]); $upd++; } else { $ins_s->execute([100,5]); $ins++; }
$chk->execute([101]); if($chk->fetch()) { $upd_s->execute([0,101]); $upd++; } else { $ins_s->execute([101,0]); $ins++; }
$chk->execute([102]); if($chk->fetch()) { $upd_s->execute([1,102]); $upd++; } else { $ins_s->execute([102,1]); $ins++; }
$chk->execute([103]); if($chk->fetch()) { $upd_s->execute([1,103]); $upd++; } else { $ins_s->execute([103,1]); $ins++; }
$chk->execute([104]); if($chk->fetch()) { $upd_s->execute([1,104]); $upd++; } else { $ins_s->execute([104,1]); $ins++; }
$chk->execute([105]); if($chk->fetch()) { $upd_s->execute([3,105]); $upd++; } else { $ins_s->execute([105,3]); $ins++; }
$chk->execute([106]); if($chk->fetch()) { $upd_s->execute([0,106]); $upd++; } else { $ins_s->execute([106,0]); $ins++; }
$chk->execute([107]); if($chk->fetch()) { $upd_s->execute([1,107]); $upd++; } else { $ins_s->execute([107,1]); $ins++; }
$chk->execute([108]); if($chk->fetch()) { $upd_s->execute([1,108]); $upd++; } else { $ins_s->execute([108,1]); $ins++; }
$chk->execute([109]); if($chk->fetch()) { $upd_s->execute([1,109]); $upd++; } else { $ins_s->execute([109,1]); $ins++; }
$chk->execute([110]); if($chk->fetch()) { $upd_s->execute([1,110]); $upd++; } else { $ins_s->execute([110,1]); $ins++; }
$chk->execute([111]); if($chk->fetch()) { $upd_s->execute([3,111]); $upd++; } else { $ins_s->execute([111,3]); $ins++; }
$chk->execute([112]); if($chk->fetch()) { $upd_s->execute([0,112]); $upd++; } else { $ins_s->execute([112,0]); $ins++; }
$chk->execute([113]); if($chk->fetch()) { $upd_s->execute([0,113]); $upd++; } else { $ins_s->execute([113,0]); $ins++; }
$chk->execute([114]); if($chk->fetch()) { $upd_s->execute([0,114]); $upd++; } else { $ins_s->execute([114,0]); $ins++; }
$chk->execute([115]); if($chk->fetch()) { $upd_s->execute([0,115]); $upd++; } else { $ins_s->execute([115,0]); $ins++; }
$chk->execute([116]); if($chk->fetch()) { $upd_s->execute([0,116]); $upd++; } else { $ins_s->execute([116,0]); $ins++; }
$chk->execute([117]); if($chk->fetch()) { $upd_s->execute([2,117]); $upd++; } else { $ins_s->execute([117,2]); $ins++; }
$chk->execute([118]); if($chk->fetch()) { $upd_s->execute([0,118]); $upd++; } else { $ins_s->execute([118,0]); $ins++; }
$chk->execute([119]); if($chk->fetch()) { $upd_s->execute([0,119]); $upd++; } else { $ins_s->execute([119,0]); $ins++; }
$chk->execute([120]); if($chk->fetch()) { $upd_s->execute([53,120]); $upd++; } else { $ins_s->execute([120,53]); $ins++; }
$chk->execute([121]); if($chk->fetch()) { $upd_s->execute([11,121]); $upd++; } else { $ins_s->execute([121,11]); $ins++; }
$chk->execute([122]); if($chk->fetch()) { $upd_s->execute([0,122]); $upd++; } else { $ins_s->execute([122,0]); $ins++; }
$chk->execute([123]); if($chk->fetch()) { $upd_s->execute([0,123]); $upd++; } else { $ins_s->execute([123,0]); $ins++; }
$chk->execute([124]); if($chk->fetch()) { $upd_s->execute([55,124]); $upd++; } else { $ins_s->execute([124,55]); $ins++; }
$chk->execute([125]); if($chk->fetch()) { $upd_s->execute([475,125]); $upd++; } else { $ins_s->execute([125,475]); $ins++; }
$chk->execute([126]); if($chk->fetch()) { $upd_s->execute([0,126]); $upd++; } else { $ins_s->execute([126,0]); $ins++; }
$chk->execute([127]); if($chk->fetch()) { $upd_s->execute([2,127]); $upd++; } else { $ins_s->execute([127,2]); $ins++; }
$chk->execute([128]); if($chk->fetch()) { $upd_s->execute([0,128]); $upd++; } else { $ins_s->execute([128,0]); $ins++; }
$chk->execute([129]); if($chk->fetch()) { $upd_s->execute([12,129]); $upd++; } else { $ins_s->execute([129,12]); $ins++; }
$chk->execute([130]); if($chk->fetch()) { $upd_s->execute([0,130]); $upd++; } else { $ins_s->execute([130,0]); $ins++; }
$chk->execute([131]); if($chk->fetch()) { $upd_s->execute([0,131]); $upd++; } else { $ins_s->execute([131,0]); $ins++; }
$chk->execute([132]); if($chk->fetch()) { $upd_s->execute([0,132]); $upd++; } else { $ins_s->execute([132,0]); $ins++; }
$chk->execute([133]); if($chk->fetch()) { $upd_s->execute([0,133]); $upd++; } else { $ins_s->execute([133,0]); $ins++; }
$chk->execute([134]); if($chk->fetch()) { $upd_s->execute([15,134]); $upd++; } else { $ins_s->execute([134,15]); $ins++; }
$chk->execute([135]); if($chk->fetch()) { $upd_s->execute([12,135]); $upd++; } else { $ins_s->execute([135,12]); $ins++; }
$chk->execute([136]); if($chk->fetch()) { $upd_s->execute([8,136]); $upd++; } else { $ins_s->execute([136,8]); $ins++; }
$chk->execute([137]); if($chk->fetch()) { $upd_s->execute([0,137]); $upd++; } else { $ins_s->execute([137,0]); $ins++; }
$chk->execute([138]); if($chk->fetch()) { $upd_s->execute([0,138]); $upd++; } else { $ins_s->execute([138,0]); $ins++; }
$chk->execute([139]); if($chk->fetch()) { $upd_s->execute([6,139]); $upd++; } else { $ins_s->execute([139,6]); $ins++; }
$chk->execute([140]); if($chk->fetch()) { $upd_s->execute([5,140]); $upd++; } else { $ins_s->execute([140,5]); $ins++; }
$chk->execute([141]); if($chk->fetch()) { $upd_s->execute([0,141]); $upd++; } else { $ins_s->execute([141,0]); $ins++; }
$chk->execute([142]); if($chk->fetch()) { $upd_s->execute([0,142]); $upd++; } else { $ins_s->execute([142,0]); $ins++; }
$chk->execute([143]); if($chk->fetch()) { $upd_s->execute([0,143]); $upd++; } else { $ins_s->execute([143,0]); $ins++; }
$chk->execute([144]); if($chk->fetch()) { $upd_s->execute([0,144]); $upd++; } else { $ins_s->execute([144,0]); $ins++; }
$chk->execute([145]); if($chk->fetch()) { $upd_s->execute([0,145]); $upd++; } else { $ins_s->execute([145,0]); $ins++; }
$chk->execute([146]); if($chk->fetch()) { $upd_s->execute([36,146]); $upd++; } else { $ins_s->execute([146,36]); $ins++; }
$chk->execute([147]); if($chk->fetch()) { $upd_s->execute([19,147]); $upd++; } else { $ins_s->execute([147,19]); $ins++; }
$chk->execute([148]); if($chk->fetch()) { $upd_s->execute([16,148]); $upd++; } else { $ins_s->execute([148,16]); $ins++; }
$chk->execute([149]); if($chk->fetch()) { $upd_s->execute([0,149]); $upd++; } else { $ins_s->execute([149,0]); $ins++; }
$chk->execute([150]); if($chk->fetch()) { $upd_s->execute([0,150]); $upd++; } else { $ins_s->execute([150,0]); $ins++; }
$chk->execute([151]); if($chk->fetch()) { $upd_s->execute([0,151]); $upd++; } else { $ins_s->execute([151,0]); $ins++; }
$chk->execute([152]); if($chk->fetch()) { $upd_s->execute([0,152]); $upd++; } else { $ins_s->execute([152,0]); $ins++; }
$chk->execute([153]); if($chk->fetch()) { $upd_s->execute([0,153]); $upd++; } else { $ins_s->execute([153,0]); $ins++; }
$chk->execute([154]); if($chk->fetch()) { $upd_s->execute([0,154]); $upd++; } else { $ins_s->execute([154,0]); $ins++; }
$chk->execute([155]); if($chk->fetch()) { $upd_s->execute([0,155]); $upd++; } else { $ins_s->execute([155,0]); $ins++; }
$chk->execute([156]); if($chk->fetch()) { $upd_s->execute([0,156]); $upd++; } else { $ins_s->execute([156,0]); $ins++; }
$chk->execute([157]); if($chk->fetch()) { $upd_s->execute([0,157]); $upd++; } else { $ins_s->execute([157,0]); $ins++; }
$chk->execute([158]); if($chk->fetch()) { $upd_s->execute([0,158]); $upd++; } else { $ins_s->execute([158,0]); $ins++; }
$chk->execute([159]); if($chk->fetch()) { $upd_s->execute([0,159]); $upd++; } else { $ins_s->execute([159,0]); $ins++; }
$chk->execute([160]); if($chk->fetch()) { $upd_s->execute([0,160]); $upd++; } else { $ins_s->execute([160,0]); $ins++; }
$chk->execute([161]); if($chk->fetch()) { $upd_s->execute([0,161]); $upd++; } else { $ins_s->execute([161,0]); $ins++; }
$chk->execute([162]); if($chk->fetch()) { $upd_s->execute([24,162]); $upd++; } else { $ins_s->execute([162,24]); $ins++; }
$chk->execute([163]); if($chk->fetch()) { $upd_s->execute([0,163]); $upd++; } else { $ins_s->execute([163,0]); $ins++; }
$chk->execute([164]); if($chk->fetch()) { $upd_s->execute([11,164]); $upd++; } else { $ins_s->execute([164,11]); $ins++; }
$chk->execute([165]); if($chk->fetch()) { $upd_s->execute([10,165]); $upd++; } else { $ins_s->execute([165,10]); $ins++; }
$chk->execute([166]); if($chk->fetch()) { $upd_s->execute([10,166]); $upd++; } else { $ins_s->execute([166,10]); $ins++; }
$chk->execute([167]); if($chk->fetch()) { $upd_s->execute([0,167]); $upd++; } else { $ins_s->execute([167,0]); $ins++; }
$chk->execute([168]); if($chk->fetch()) { $upd_s->execute([0,168]); $upd++; } else { $ins_s->execute([168,0]); $ins++; }
$chk->execute([169]); if($chk->fetch()) { $upd_s->execute([0,169]); $upd++; } else { $ins_s->execute([169,0]); $ins++; }
$chk->execute([170]); if($chk->fetch()) { $upd_s->execute([0,170]); $upd++; } else { $ins_s->execute([170,0]); $ins++; }
$chk->execute([171]); if($chk->fetch()) { $upd_s->execute([0,171]); $upd++; } else { $ins_s->execute([171,0]); $ins++; }
$chk->execute([172]); if($chk->fetch()) { $upd_s->execute([0,172]); $upd++; } else { $ins_s->execute([172,0]); $ins++; }
$chk->execute([173]); if($chk->fetch()) { $upd_s->execute([8,173]); $upd++; } else { $ins_s->execute([173,8]); $ins++; }
$chk->execute([174]); if($chk->fetch()) { $upd_s->execute([0,174]); $upd++; } else { $ins_s->execute([174,0]); $ins++; }
$chk->execute([175]); if($chk->fetch()) { $upd_s->execute([17,175]); $upd++; } else { $ins_s->execute([175,17]); $ins++; }
$chk->execute([176]); if($chk->fetch()) { $upd_s->execute([0,176]); $upd++; } else { $ins_s->execute([176,0]); $ins++; }
$chk->execute([177]); if($chk->fetch()) { $upd_s->execute([0,177]); $upd++; } else { $ins_s->execute([177,0]); $ins++; }
$chk->execute([178]); if($chk->fetch()) { $upd_s->execute([0,178]); $upd++; } else { $ins_s->execute([178,0]); $ins++; }
$chk->execute([179]); if($chk->fetch()) { $upd_s->execute([6,179]); $upd++; } else { $ins_s->execute([179,6]); $ins++; }
$chk->execute([180]); if($chk->fetch()) { $upd_s->execute([0,180]); $upd++; } else { $ins_s->execute([180,0]); $ins++; }
$chk->execute([181]); if($chk->fetch()) { $upd_s->execute([8,181]); $upd++; } else { $ins_s->execute([181,8]); $ins++; }
$chk->execute([182]); if($chk->fetch()) { $upd_s->execute([4,182]); $upd++; } else { $ins_s->execute([182,4]); $ins++; }
$chk->execute([183]); if($chk->fetch()) { $upd_s->execute([10,183]); $upd++; } else { $ins_s->execute([183,10]); $ins++; }
$chk->execute([184]); if($chk->fetch()) { $upd_s->execute([0,184]); $upd++; } else { $ins_s->execute([184,0]); $ins++; }
echo 'Done! inserted='.$ins.' updated='.$upd;
?>